models:
  - name: "gpt-4.1"
    input_cost_per_million_tokens: 2.00
    output_cost_per_million_tokens: 8.00
    score: 4.89
  - name: "gpt-4.1-mini"
    input_cost_per_million_tokens: 0.40
    output_cost_per_million_tokens: 1.60
    score: 4.73
  - name: "gemini-2.5-flash-preview"
    input_cost_per_million_tokens: 0.15
    output_cost_per_million_tokens: 3.5
    score: 4.84
  - name: "google/gemini-2.0-flash-001"
    input_cost_per_million_tokens: 0.100
    output_cost_per_million_tokens: 0.400
    score: 4.82
  - name: "grok-3-mini-beta"
    input_cost_per_million_tokens: 0.3
    output_cost_per_million_tokens: 0.5
    score: 4.79
  - name: "gemini-flash-1.5-8b"
    input_cost_per_million_tokens: 0.038
    output_cost_per_million_tokens: 0.15
    score: 4.45
  # - name: "openai-o3"
  #   input_cost_per_million_tokens: 10.00
  #   cached_input_cost_per_million_tokens: 2.50
  #   output_cost_per_million_tokens: 40.00
  # - name: "openai-o4-mini"
  #   input_cost_per_million_tokens: 1.100
  #   cached_input_cost_per_million_tokens: 0.275
  #   output_cost_per_million_tokens: 4.400
  #   score: 8.00
  # - name: "openai-o4"
  #   input_cost_per_million_tokens: 2.50
  #   cached_input_cost_per_million_tokens: 1.25
  #   output_cost_per_million_tokens: 10.00
  #   score: 8.76
DEEPL_COST_PER_MILLION_WORDS: 20.00
TOKEN_TO_WORDS_RATIO: 0.8
TOTAL_WORDS: 821125755
TOTAL_CHARS: 4541649687
ROMANIAN_TO_ENGLISH_RATIO: 1.20