models:
  - name: "gpt-4.1"
    input_cost_per_million_tokens: 2.00
    cached_input_cost_per_million_tokens: 0.50
    output_cost_per_million_tokens: 8.00
    score: 9.14
  - name: "gpt-4.1-mini"
    input_cost_per_million_tokens: 0.40
    cached_input_cost_per_million_tokens: 0.10
    output_cost_per_million_tokens: 1.60
    score: 8.80
  - name: "gpt-4.1-nano"
    input_cost_per_million_tokens: 0.100
    cached_input_cost_per_million_tokens: 0.025
    output_cost_per_million_tokens: 0.400
    score: 7.48
  # - name: "openai-o3"
  #   input_cost_per_million_tokens: 10.00
  #   cached_input_cost_per_million_tokens: 2.50
  #   output_cost_per_million_tokens: 40.00
  # - name: "openai-o4-mini"
  #   input_cost_per_million_tokens: 1.100
  #   cached_input_cost_per_million_tokens: 0.275
  #   output_cost_per_million_tokens: 4.400
  #   score: 8.00
  # - name: "openai-o4"
  #   input_cost_per_million_tokens: 2.50
  #   cached_input_cost_per_million_tokens: 1.25
  #   output_cost_per_million_tokens: 10.00
  #   score: 8.76
DEEPL_COST_PER_MILLION_WORDS: 20.00
TOKEN_TO_WORDS_RATIO: 0.8
TOTAL_WORDS: 821125755
TOTAL_CHARS: 4541649687
ROMANIAN_TO_ENGLISH_RATIO: 1.20